### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by travisreed-wf**

### CODE REVIEW

**Review by travisreed-wf — COMMENTED** [review]
a

**Review by travisreed-wf — COMMENTED** [review]
b

**Review by travisreed-wf — COMMENTED** [review]
c

**Review by travisreed-wf — COMMENTED** [review]
d

**Review by travisreed-wf — COMMENTED** [review]
e

**Review by travisreed-wf — COMMENTED** [review]
f

**Review by travisreed-wf — COMMENTED** [review]
g

**Review by travisreed-wf — COMMENTED** [review]
h

**Review by travisreed-wf — COMMENTED** [review]
i

**Review by travisreed-wf — COMMENTED** [review]
j

**Review by travisreed-wf — COMMENTED** [review]
k

**Review by travisreed-wf — COMMENTED** [review]
l

**Review by travisreed-wf — COMMENTED** [review]
m

**Review by travisreed-wf — COMMENTED** [review]
n

**Review by travisreed-wf — COMMENTED** [review]
o

**Review by travisreed-wf — COMMENTED** [review]
p

**Review by travisreed-wf — COMMENTED** [review]
q

**Review by travisreed-wf — COMMENTED** [review]
r

**Review by travisreed-wf — COMMENTED** [review]
s

**Review by travisreed-wf — COMMENTED** [review]
t

**Review by travisreed-wf — COMMENTED** [review]
u

**Comment by aguibert** [comment]
@travisreed-wf what are you doing?

**Comment by travisreed-wf** [comment]
demoing a github bug on an open source repo so that I dont have to give them access to a Workiva repo

**Review by travisreed-wf — COMMENTED** [review]
v

**Review by travisreed-wf — COMMENTED** [review]
w

**Review by travisreed-wf — COMMENTED** [review]
x

**Review by travisreed-wf — COMMENTED** [review]
y

**Review by travisreed-wf — COMMENTED** [review]
z

**Review by travisreed-wf — COMMENTED** [review]
1

**Review by travisreed-wf — COMMENTED** [review]
2

**Review by travisreed-wf — COMMENTED** [review]
3

**Review by travisreed-wf — COMMENTED** [review]
4

**Review by travisreed-wf — COMMENTED** [review]
5

**Review by travisreed-wf — COMMENTED** [review]
6

**Comment by jdmielke** [comment]
I think this addition to the readme really added a lot. +1

**Pull request closed without merging**
